增加文件，提交评审
DingTobest/test pull request #4
Opened 2021-07-08 06:21 UTC by ProductTestD

创建提交信息

2021-07-08 06:26 UTC, DingTobest commented on OuterInnerVariableRef.java
> +    // 增加第二处扫描信息
此处不通过，修改一下提示信息
```suggestion
    // 测试测试
```

> test
  
Duplicate of #`代码`
#2

2021-07-08 06:28 UTC, DingTobest requested changes
必须修改完成后再提交

2021-07-08 06:28 UTC, DingTobest commented on SimpleDemo.java
> +    // 增加提示信息第一处
第二处信息，需要修改
```suggestion
    // 第二处测试
```

2021-07-08 06:32 UTC, ProductTestD commented on OuterInnerVariableRef.java
> +    // 增加第二处扫描信息
此处我觉得是正确的，不需要

2021-07-08 06:35 UTC, ProductTestD commented on BaseDemo.java
> +        for (int i = 0; i < 5; i++) {
这块我觉得我写的还挺好

2021-07-08 06:38 UTC, DingTobest approved these changes
看你说了这么多，最后就通过吧

2021-07-08 06:45 UTC, DingTobest approved these changes

2021-07-08 08:24 UTC, DingTobest commented
> 看你说了这么多，最后就通过吧

test

2021-07-14 03:24 UTC, DingTobest commented on BaseStructure.java
> +    }
```suggestion
    public BaseStructure() {
        this.f1 = "bb";
    }
```

2021-07-14 03:25 UTC, DingTobest commented on BaseStructure.java
> +    }
```suggestion
            target = target;
        }
        target = this.f1;
        m2(target);
        ArrayList<String> stringString = new ArrayList<String>();
        stringString.remove(target);
        int index = stringString.indexOf("v");
        return target;
    }
    
    test

    public String m2(String p1) {
        String r = p1;
        return r;
    }
```

2021-07-20 07:56 UTC, DingTobest commented on BaseDemo.java
> +
```suggestion

public class BaseDemo {
···
```

2021-07-20 07:56 UTC, DingTobest commented on BaseStructure.java
> +public class BaseStructure {
```suggestion

import com.baidu.bugbye.bca.supporter.Student;

import java.util.ArrayList;

public class BaseStructure {

ttt
```

2021-08-10 12:50 UTC, DingTobest commented on OuterInnerVariableRef.java
> +    // 增加第二处扫描信息
aaa

2021-08-12 08:35 UTC, suwei007 commented on OuterInnerVariableRef.java
> +    // 增加第二处扫描信息
我看看

2021-08-25 06:40 UTC, DingTobest requested changes
不行，这个打回重做123

2021-08-25 06:40 UTC, DingTobest commented on BaseDemo.java
> +        } finally {
这个地方需要修改

2021-08-25 06:42 UTC, DingTobest requested changes

2021-08-25 06:42 UTC, DingTobest commented on BaseDemo.java
> +        if (null != one && null == two) {
```suggestion
    }

    public void strange() {
        Object one112 = ObjectGenerator.getObject();
        Object two = ObjectGenerator.getObject();
        if (null != one && null == two) {
```

2021-09-06 06:24 UTC, DingTobest reviewed
测试

2021-09-06 06:24 UTC, DingTobest commented
普通评论测试

2021-09-06 07:59 UTC, DingTobest commented on BaseStructure.java
> +        } else {
ttt

2021-09-06 08:01 UTC, DingTobest commented on BaseDemo.java
> +package com.baidu.bugbye.bca.demo;
首行测试

2021-09-06 08:02 UTC, DingTobest commented on DataFlow.java
> +            case 1:
测试

2021-09-06 08:03 UTC, DingTobest commented on DataFlow.java
> +    public void demo5() {
测试2

2021-09-06 08:12 UTC, DingTobest commented
> 看你说了这么多，最后就通过吧

测试回复

2021-09-07 06:58 UTC, DingTobest commented on DataFlow.java
> +    public void demo5() {
test

2021-09-07 08:25 UTC, DingTobest commented
安安分分

2021-09-07 08:26 UTC, DingTobest commented
> 安安分分

test

2021-09-07 10:48 UTC, DingTobest commented on BaseStructure.java
> +import com.baidu.bugbye.bca.supporter.Student;
啊啊啊发

2021-09-07 10:50 UTC, DingTobest commented on DataFlow.java
> +    public void demo6() {
test

2021-09-08 03:48 UTC, DingTobest reviewed
aaa

2021-09-08 03:48 UTC, DingTobest commented on BaseDemo.java
> +
test3

2021-09-09 03:02 UTC, liuyanqiu123 requested changes
这个地方必须修改完才能审核通过

2021-09-10 08:34 UTC, DingTobest approved these changes
同意

2021-09-10 08:34 UTC, DingTobest approved these changes
再次同意

2021-09-15 09:29 UTC, DingTobest commented
1

2021-09-15 09:29 UTC, DingTobest commented
2

2021-09-15 09:29 UTC, DingTobest commented
3

2021-09-15 09:29 UTC, DingTobest commented
4

2021-09-15 09:29 UTC, DingTobest commented
5

2021-09-15 09:29 UTC, DingTobest commented
6

2021-09-15 09:29 UTC, DingTobest commented
7

2021-09-15 09:29 UTC, DingTobest commented
8

2021-09-15 09:29 UTC, DingTobest commented
9

2021-09-15 09:29 UTC, DingTobest commented
10

2021-09-15 09:29 UTC, DingTobest commented
11

2021-09-15 09:29 UTC, DingTobest commented
12

2021-09-15 09:29 UTC, DingTobest commented
13

2021-09-15 09:29 UTC, DingTobest commented
14

2021-09-15 09:29 UTC, DingTobest commented
15

2021-09-15 09:29 UTC, DingTobest commented
16

2021-09-15 09:29 UTC, DingTobest commented
17

2021-09-15 09:29 UTC, DingTobest commented
18

2021-09-15 09:29 UTC, DingTobest commented
19

2021-09-15 09:29 UTC, DingTobest commented
20

2021-09-15 09:30 UTC, DingTobest commented
21

2021-09-15 09:30 UTC, DingTobest commented
22

2021-09-15 09:30 UTC, DingTobest commented
23

2021-09-15 09:30 UTC, DingTobest commented
24

2021-09-15 09:30 UTC, DingTobest commented
25

2021-09-15 09:30 UTC, DingTobest commented
26

2021-09-15 09:30 UTC, DingTobest commented
27

2021-09-15 09:30 UTC, DingTobest commented
28

2021-09-15 09:30 UTC, DingTobest commented
29

2021-09-15 09:30 UTC, DingTobest commented
30

2021-09-15 09:30 UTC, DingTobest commented
31

2021-09-15 09:30 UTC, DingTobest commented
32

2021-09-15 09:30 UTC, DingTobest commented
33

2021-09-15 09:30 UTC, DingTobest commented
34

2021-09-15 09:31 UTC, DingTobest commented
35

2021-09-15 09:31 UTC, DingTobest commented
36

2021-09-15 09:31 UTC, DingTobest commented
37

2021-09-15 09:31 UTC, DingTobest commented
38

2021-09-15 09:31 UTC, DingTobest commented
39

2021-09-15 09:31 UTC, DingTobest commented
40

2021-09-17 06:21 UTC, DingTobest commented on BaseStructure.java
> +    }
t

2021-09-17 06:22 UTC, DingTobest commented on BaseStructure.java
> +    }
test

2021-09-17 06:22 UTC, DingTobest commented on BaseStructure.java
> +    }
> t

test

2021-09-17 06:23 UTC, DingTobest commented on BaseDemo.java
> +package com.baidu.bugbye.bca.demo;
> 首行测试

test

2021-09-17 09:05 UTC, DingTobest commented
aaaaa

2021-09-27 09:02 UTC, DingTobest commented on BaseDemo.java
> +        if (null != one && null == two) {
> 

test

2021-10-08 03:46 UTC, DingTobest commented on SimpleDemo.java
> +    // 增加提示信息第一处
test3

2021-10-19 06:30 UTC, suwei007 commented
> aaaaa

2022-01-10 06:50 UTC, DingTobest commented on BaseStructure.java
> +        target = m2(target);
```suggestion
        int intint = 666;
        new Integer(intint);
        String a = "a";
        String target = "resultvalue",temp="temp";
        target = m2(target);
```

2025-07-07 07:55 UTC, closed without merging